version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
        MYSQL_ROOT_PASSWORD: prakash123
        MYSQL_DATABASE: product
        MYSQL_USER: prakash
        MYSQL_PASSWORD: password123
    ports:
         - "3307:3306"
    volumes:
        - mysql-data:/var/lib/mysql
    networks:
        - product-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  product-service:
    build: .
    image: product-service
    container_name: product-service
    environment:
      DB_HOST: mysql-db
      DB_USERNAME: prakash
      DB_PASSWORD: password123
    ports:
      - "8089:8089"
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
        - product-network

networks:
    product-network:
        driver: bridge

volumes:
    mysql-data:
